/* tslint:disable */
/* eslint-disable */
/**
 * @pjore/app1
 * DigitalOffice app1 is the main backend of DigitalOffice. It provides an API with primary purpose to serve the DigitalOffice app (ie. the frontend). To use the API you need to authenticate using public/signin endpoint. This will generate an token that needs to be passed as bearer token in every request
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

