# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Create release

on:
  #push:
   # branches:
    #- main
    #paths:
    #- apps/**
    #- packages/**
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout source code"
      uses: "actions/checkout@v3"
    - name: "Bump version"
      uses: "phips28/gh-action-bump-version@master"
      id: version-bump
      with:
        tag-prefix: ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get tag name from ref
      shell: bash
      run: |
        echo "RELEASE_TAG=${{ steps.version-bump.outputs.newTag }}" >> $GITHUB_OUTPUT
      id: get_tag
    - name: Build changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@main
      with:
        configuration: 'release-changelog-builder-config.json'
      env:
        GITHUB_TOKEN: ${{ secrets.PJORE_PAT }}
    - name: Create release in main
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.PJORE_PAT }}
        tag_name: ${{ steps.get_tag.outputs.RELEASE_TAG }}
        name: Release ${{ steps.get_tag.outputs.RELEASE_TAG }}
        body: ${{steps.build_changelog.outputs.changelog}}
        draft: false
        prerelease: false